### ISSUE TITLE
feature request: block / filter keywords

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Baertram/pChat#10]
I was wondering if this is something that might be integrated... maybe in the ANTI SPAM section there would be another input field below list of nicknames that if a keyword was mentioned it would just remove that entry from chat box... **WOULD BE GREAT!**

**Comment by Baertram** [comment]
Yeah, could be added but there exist already addons doing this with more features and details, so I'm not going to include this into pChat (due to time and amount of addons to update) ;-)

Please use on of the others in combination, like for example:
https://www.esoui.com/downloads/info3032-AdBlockPlus-BlockChatAdvertisementsSpamMore.html
https://www.esoui.com/downloads/info3319-RoyaleWithCheeseChatFilter.html
https://www.esoui.com/downloads/info2328-CyrillicChatFilter.html
https://www.esoui.com/downloads/info2544-CleanMyChat.html#comments

**Comment by Baertram** [comment]
Feature not possible atm due to time needed to add and especialyl test with all the other compatible addons... Sorry
